branches: [master]
pipeline:
  compile:
    image: ekidd/rust-musl-builder
    commands:
      - cargo
      - build
      - --release
  publish:
    image: plugins/docker
    repo: 127labs/yakp
    username: ${DOCKER_USERNAME}
    password: ${DOCKER_PASSWORD}
    email: imran@127labs.com
    tags:
      - latest
      - ${DRONE_COMMIT_SHA}
