pipeline:
  test:
    image: clux/muslrust
    commands:
      - cargo test
  build:
    image: clux/muslrust
    commands:
      - cargo build --release
    when:
      branch: master
      event: push
  publish:
    image: plugins/docker
    repo: 127labs/drone-k8s-helm
    tags:
      - latest
    secrets:
      - docker_username
      - docker_password
    when:
      branch: master
      event: push
