[package]
name = "drone-k8s-helm"
version = "0.1.0"
authors = ["Imran Ismail <imran@127labs.com>", "Faris Amali Alis <faris@127labs.com>"]

[dependencies]
regex = "0.2"
handlebars = "0.27.0"
serde_json = "1.0"
